# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findweights <- function(origNodes, inbag, nodes, nobs, nnew, ntree) {
    .Call('_abcrf_findweights', PACKAGE = 'abcrf', origNodes, inbag, nodes, nobs, nnew, ntree)
}

oobErrors <- function(sequo, ntrain, mod, ntree, modindex, inbag, mimi) {
    .Call('_abcrf_oobErrors', PACKAGE = 'abcrf', sequo, ntrain, mod, ntree, modindex, inbag, mimi)
}

oobErrorsReg <- function(sequo, ntrain, ntree, resp, inbag, pred) {
    .Call('_abcrf_oobErrorsReg', PACKAGE = 'abcrf', sequo, ntrain, ntree, resp, inbag, pred)
}

oobMedErrorsReg <- function(sequo, ntrain, ntree, resp, inbag, pred) {
    .Call('_abcrf_oobMedErrorsReg', PACKAGE = 'abcrf', sequo, ntrain, ntree, resp, inbag, pred)
}

predictOob_cpp <- function(origNodes, inbag, nobs, ntree) {
    .Call('_abcrf_predictOob_cpp', PACKAGE = 'abcrf', origNodes, inbag, nobs, ntree)
}

